# Generated by Django 5.0.4 on 2024-05-23 09:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('state', models.CharField(choices=[('PR', 'Production'), ('TR', 'Training'), ('DE', 'Development'), ('AR', 'Archived')], max_length=2)),
                ('status', models.CharField(choices=[('IN', 'Inactive'), ('AC', 'Active'), ('AR', 'Archived')], max_length=2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('saved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('score', models.IntegerField(default=0)),
                ('path', models.FileField(upload_to='models/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['h5', 'pkl'])])),
                ('state', models.CharField(choices=[('PR', 'Production'), ('TR', 'Training'), ('DE', 'Development'), ('AR', 'Archived')], default='DE', max_length=2)),
                ('status', models.CharField(choices=[('IN', 'Inactive'), ('AC', 'Active'), ('AR', 'Archived')], default='IN', max_length=2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('experience_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website.experience')),
                ('saved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
