# Generated by Django 5.0.4 on 2024-05-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='state',
            field=models.CharField(choices=[('PR', 'Production'), ('TR', 'Training'), ('DE', 'Development'), ('AR', 'Archived')], default='DE', max_length=2),
        ),
        migrations.AlterField(
            model_name='experience',
            name='status',
            field=models.CharField(choices=[('IN', 'Inactive'), ('AC', 'Active'), ('AR', 'Archived')], default='IN', max_length=2),
        ),
    ]
