# Generated by Django 5.0.4 on 2024-05-23 10:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_experience_description_alter_experience_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deploiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('IN', 'Inactive'), ('AC', 'Active'), ('AR', 'Archived')], default='IN', max_length=2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('experience_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website.experience')),
                ('model_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website.model')),
                ('saved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
