# Generated by Django 5.0.4 on 2024-05-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_deploiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploiement',
            name='state',
            field=models.CharField(choices=[('PR', 'Production'), ('TR', 'Training'), ('DE', 'Development'), ('AR', 'Archived')], default='DE', max_length=2),
        ),
    ]
