# Generated by Django 5.0.4 on 2024-05-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_deploiement_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploiement',
            name='state',
            field=models.CharField(choices=[('PR', 'Production'), ('TR', 'Training'), ('DE', 'Development'), ('AR', 'Archived')], default='DE', max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='deploiement',
            name='status',
            field=models.CharField(choices=[('IN', 'Inactive'), ('AC', 'Active'), ('AR', 'Archived')], default='IN', max_length=2, unique=True),
        ),
    ]
