# Generated by Django 5.0.4 on 2024-05-23 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_deploiement_state_alter_deploiement_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deploiement',
            old_name='experience_id',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='deploiement',
            old_name='model_id',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='experience_id',
            new_name='experience',
        ),
    ]
