# Generated by Django 5.0.4 on 2024-05-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30)),
                ('libelle', models.CharField(max_length=100)),
                ('discribe', models.CharField(max_length=250)),
                ('score', models.IntegerField()),
                ('path', models.CharField(max_length=100)),
                ('state', models.BooleanField()),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
