# Generated by Django 5.0.4 on 2024-05-02 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='discribe',
            new_name='description',
        ),
    ]
