# Generated by Django 5.0.4 on 2024-05-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_discribe_model_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='path',
            field=models.FileField(upload_to='models/'),
        ),
    ]
